### ISSUE TITLE
ProcessHighDensityRegionAlgorithm does not work on OT 1.15

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/othdrplot#37]
```
processSample = ot.ProcessSample(mesh, n_fields, d_fields)

for i in range(n_fields):
    trajectory = ot.Sample(donnees_temperature[i, :], 1)
    processSample[i] = ot.Field(mesh, trajectory)

hdr = ProcessHighDensityRegionAlgorithm(processSample)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/A61372/miniconda3/lib/python3.7/site-packages/othdrplot-1.0.1-py3.7.egg/othdrplot/process_high_density_region_algorithm.py", line 39, in __init__
  File "/home/A61372/miniconda3/lib/python3.7/site-packages/openturns/typ.py", line 9463, in Sample___getattribute__
    return super(Sample, self).__getattribute__(name)
AttributeError: 'Sample' object has no attribute 'getValues'
```

**Comment by sofianehaddad** [comment]
it is due to https://github.com/openturns/openturns/pull/1458/commits/30da434f21be48ec3d53111c014479477db29cca
